server:
  port: 8004

#应用名称及验证账号
spring:
  application:
    name: service-order-dispatch
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 100

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online-taxi?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-total: 5
      max-wait-millis: 200
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://127.0.0.1:7900/eureka/
    registry-fetch-interval-seconds: 30
  instance:
    lease-renewal-interval-in-seconds: 30


services:
  address:
    - account: http://localhost:8081
    - dispatch: http://localhost:8082
    - order: http://localhost:8083
    - map: http://localhost:8084
    - message: http://localhost:8085
    - netty: http://localhost:8086
    - pay: http://localhost:8087
    - valuation: http://localhost:8088
    - file: http://localhost:8089
    - government: http://localhost:9999


oss:
  file:
    url: http://yeyangshu.oss-cn-hangzhou.aliyuncs.com/