package com.yeyangshu.servicepassengeruser.mapper;

import com.yeyangshu.internalcommon.entity.PassengerRegisterSource;

/**
 * @author yeyangshu
 * @version 1.0
 * @date 2020/10/31 13:55
 */
public interface PassengerRegisterSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_register_source
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_register_source
     *
     * @mbggenerated
     */
    int insert(PassengerRegisterSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_register_source
     *
     * @mbggenerated
     */
    int insertSelective(PassengerRegisterSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_register_source
     *
     * @mbggenerated
     */
    PassengerRegisterSource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_register_source
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PassengerRegisterSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_passenger_register_source
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PassengerRegisterSource record);
}